### ISSUE TITLE
Signing in

### ISSUE THREAD

**Issue by M4GNV5** [ajsb85/instantbird-addon-hipchat#2]
Hey

When Instantbird asks me for a username... what do i type in?
i tried my name, my email and my api token but nothing worked :(
I just dont get it :/

**Comment by ajsb85** [comment]
- Go to the “Add Account” window
- Protocol: Select “HipChat”
- Username: Enter your username from from this page: https://www.hipchat.com/account/xmpp
-  Server: “chat.hipchat.com”
-  Password: Your HipChat account password
-  Click “Add”

You should now see your HipChat contacts appear in your buddylist.
